# Generated by Django 4.0.4 on 2022-05-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('parent_message', models.IntegerField()),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.topicmodel')),
            ],
        ),
    ]
